For #831: Absolute volume control
File-New-Project/EarTrumpet pull request #1084
Opened 2022-03-10 12:15 UTC by Taknok

## Implement an absolute volume control

A user can register 2 keys to control volume globally across all devices. A user muting a device with "normal" control cannot unmute with absolute control to prevent unwanted unmute.

The function `AbsoluteVolumeIncrement` and `AbsoluteVolumeDecrement` are in `App.xaml.xs` because I did not know if a new dedicated file is wanted for a such small addition or not. Tell me if you want to change the architecture to a cleaner structure.

The `absMuted` property is not set in the stream level because I did not see the value to set this low in the architecture. It is only needed by AudioSession. Again, I can change the location if wanted.

Compilation and run:
- [x] Debug
- [x] Release
- [x] VSDebug

=> Referred issue/discussion #831

2022-03-10 12:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/File-New-Project/EarTrumpet?pullRequest=1084) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/File-New-Project/EarTrumpet?pullRequest=1084) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: josh-hemphill<br/>:white_check_mark: riverar<br/>:x: Taknok<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/File-New-Project/EarTrumpet?pullRequest=1084) it.</sub>

2022-03-16 01:09 UTC, Taknok commented
It seems that the build failed due to a dotnet SDK misconfiguration in the CI rather than the changes done by my code. Am I wrong ? :/

2022-03-24 17:46 UTC, aloisdg commented on EarTrumpet/App.xaml.cs
> +                }
If `AllDevices` is an Enumerable, we should be able to write:

           foreach (var device in CollectionViewModel.AllDevices.Where(d => !d.IsMuted))
           {
                // if device is not muted but will be muted by 
                bool wasMuted = device.IsMuted;
                // device.IncrementVolume(-2);
                device.Volume -= 2;
                // if device is muted by this absolute down
                // .IsMuted is not already updated
                if (!wasMuted == (device.Volume <= 0))
                {
                    device.absMuted = true;
                }
            }

2022-03-24 17:51 UTC, aloisdg commented on EarTrumpet/App.xaml.cs
> +        }
If `AllDevices` is an Enumerable, we should be able to write:

            foreach (var device in CollectionViewModel.AllDevices.Where(d => !d.IsMuted || d.absMuted))
            {
                // in any case this device is not abs muted anymore
                device.absMuted = false;
                device.IncrementVolume(2);
            }
            
Note that `!(a && !b)` is `!a || b`

2022-03-24 18:34 UTC, Taknok commented
Thank you for the proposals !

2022-03-24 20:13 UTC, Taknok commented
I will try to remove and reclone my project, because I have not this error on my computer.  This is strange, the resource "missing" is added in the commit https://github.com/File-New-Project/EarTrumpet/pull/1084/commits/0291aa0d544af4002c3c57367db7635cb9e9e718 ... along with the down version, which does not trigger any error. I compared both string and they are equals.

2022-03-24 20:14 UTC, riverar commented
Merge from dev, will resolve the build failures since I made pipelines change there 😃

2022-03-24 21:06 UTC, Taknok commented
No there is an issue... The branch is rebased in the latest dev. When I re-cloned the error code is returned at compilation, when re-saving the `Resources.resx` the compilation is working, but nothing is shown as modified in git status ... I tried CRLF/LF and nothing. I will investigate...

2022-03-24 21:10 UTC, riverar commented
Oh I see, different error ```
D:\a\EarTrumpet\EarTrumpet\EarTrumpet\UI\Views\SettingsWindow.xaml(110,62): error MC3011: Cannot find the static member 'SettingsAbsoluteVolumeUpText' on the type 'Resources'
```

Will let you investigate :)

2022-03-24 21:27 UTC, Taknok commented
By updating the `ResourceBuilder` from 16 to 17, the issue is gone in `Resources.Designer.cs` 47f65276126c2f0af8313fccc86510c5dc9471ee

2022-04-27 05:07 UTC, Taknok commented
Any update on this ?

2022-04-30 22:50 UTC, riverar commented
Tested this locally, works fine. Will go through PR now, thanks for your patience.

2022-04-30 23:09 UTC, riverar requested changes

2022-04-30 23:09 UTC, riverar commented on EarTrumpet/App.xaml.cs
> +
Nit: Extra line
```suggestion

```

2022-04-30 23:09 UTC, riverar commented on EarTrumpet/App.xaml.cs
> +            foreach (var device in CollectionViewModel.AllDevices.Where(d => !d.IsMuted || d.absMuted))
Nit: PascalCase public properties (and start with Is/Has)
```suggestion
            foreach (var device in CollectionViewModel.AllDevices.Where(d => !d.IsMuted || d.IsAbsMuted))
```

2022-04-30 23:09 UTC, riverar commented on EarTrumpet/Properties/Resources.resx
> +  </data>
```suggestion
  <data name="SettingsAbsoluteVolumeDownText" xml:space="preserve">
    <value>Decrease volume for all devices</value>
  </data>
  <data name="SettingsAbsoluteVolumeUpText" xml:space="preserve">
    <value>Increase volume for all devices</value>
  </data>
```

2022-04-30 23:09 UTC, riverar commented on EarTrumpet/UI/ViewModels/AudioSessionViewModel.cs
> +        private bool _absMuted;
Nit: 
```suggestion
        private bool _isAbsMuted;
```

2022-04-30 23:11 UTC, riverar commented
One thing you may want to look at (not a blocker for this PR): Holding the absolute shortcut down does not show changes in the UI and the app hangs while processing the events. This does not happen with our normal shortcut.

As soon as the minor PR nits are addressed I'll merge it in. Thanks again!

2022-05-01 07:26 UTC, Taknok commented
On, I will try to fix this. I keep you updated.

2022-05-03 07:30 UTC, Taknok commented
Converted to draft while adjusting shortcut processing

2022-05-06 00:04 UTC, riverar commented
From build logs, just a friendly ping.
```
D:\a\EarTrumpet\EarTrumpet\EarTrumpet\App.xaml.cs(275,28): error CS1061: 'DeviceViewModel' does not contain a definition for 'absMuted' and no accessible extension method 'absMuted' accepting a first argument of type 'DeviceViewModel' could be found (are you missing a using directive or an assembly reference?) [D:\a\EarTrumpet\EarTrumpet\EarTrumpet\EarTrumpet_1lnm3op3_wpftmp.csproj
```

2022-05-06 08:43 UTC, Taknok commented
Yes, I "drafted" the PR the time I get access to a computer to make a proper edit: replace all variables name, search the shortcut freeze and test a build.

2022-05-12 21:24 UTC, Taknok commented
> Holding the absolute shortcut down does not show changes in the UI and the app hangs while processing the events.

What version of windows are you using ? Because I do not have this behavior :/

https://user-images.githubusercontent.com/12498020/168170545-72043281-7404-4193-aa57-9bef108cd0f0.mp4

2022-05-15 17:28 UTC, riverar approved these changes

2022-05-15 17:31 UTC, merged

2022-05-15 17:31 UTC, riverar commented
Thanks again @Taknok! This is now in dev builds, will get it pushed out to the retail channel soon.